"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class CheaterState(object):
    __slots__ = ["orientation", "position", "omegaBody", "vBody", "acceleration"]

    __typenames__ = ["float", "float", "float", "float", "float"]

    __dimensions__ = [[4], [3], [3], [3], [3]]

    def __init__(self):
        self.orientation = [ 0.0 for dim0 in range(4) ]
        self.position = [ 0.0 for dim0 in range(3) ]
        self.omegaBody = [ 0.0 for dim0 in range(3) ]
        self.vBody = [ 0.0 for dim0 in range(3) ]
        self.acceleration = [ 0.0 for dim0 in range(3) ]

    def encode(self):
        buf = BytesIO()
        buf.write(CheaterState._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack('>4f', *self.orientation[:4]))
        buf.write(struct.pack('>3f', *self.position[:3]))
        buf.write(struct.pack('>3f', *self.omegaBody[:3]))
        buf.write(struct.pack('>3f', *self.vBody[:3]))
        buf.write(struct.pack('>3f', *self.acceleration[:3]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != CheaterState._get_packed_fingerprint():
            raise ValueError("Decode error")
        return CheaterState._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = CheaterState()
        self.orientation = struct.unpack('>4f', buf.read(16))
        self.position = struct.unpack('>3f', buf.read(12))
        self.omegaBody = struct.unpack('>3f', buf.read(12))
        self.vBody = struct.unpack('>3f', buf.read(12))
        self.acceleration = struct.unpack('>3f', buf.read(12))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if CheaterState in parents: return 0
        tmphash = (0x23f25dabb674d8d5) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if CheaterState._packed_fingerprint is None:
            CheaterState._packed_fingerprint = struct.pack(">Q", CheaterState._get_hash_recursive([]))
        return CheaterState._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

